######################################################################
# Automatically generated by qmake (3.1) Sat Sep 21 00:03:21 2024
######################################################################
QT += core gui widgets

TEMPLATE = app
TARGET = desktop

INCLUDEPATH += .
INCLUDEPATH += $$PWD/../../brick_game/api

CONFIG -= app_bundle
CONFIG += c++17

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += Drawing.hpp \
           GameWidget.hpp \
           MainWindow.hpp \
           ../../brick_game/api/struct.h \
           ../../brick_game/api/apiBG.h \

SOURCES += Drawing.cpp \
           GameWidget.cpp \
           MainWindow.cpp \
           BrickGamesDesktop.cpp \

BRIDGE_LIB_DIR = $$BRIDGE_LIB_DIR
isEmpty(BRIDGE_LIB_DIR) {
    BRIDGE_LIB_DIR = $$PWD/../../build/lib
}

BRIDGE_RPATH = $$BRIDGE_RPATH
isEmpty(BRIDGE_RPATH) {
    BRIDGE_RPATH = @executable_path/../build/lib
}

LIBS += -L$$BRIDGE_LIB_DIR -lClientBridge
QMAKE_LFLAGS += -Wl,-rpath,$$BRIDGE_RPATH
