######################################################################
# Automatically generated by qmake (3.1) Sat Sep 21 00:03:21 2024
######################################################################
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = desktop
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += Drawing.hpp \
           GameApi.hpp \
           GameWidget.hpp \
           MainWindow.hpp \
           ../../brick_game/struct.h \
           ../../brick_game/snake/wrapper/SnakeWrapper.h \
           ../../brick_game/tetris/controller_tetris.h \

SOURCES += Drawing.cpp \
           GameWidget.cpp \
           MainWindow.cpp \
           BrickGamesDesktop.cpp \

CONFIG -= app_bundle

# Include paths for headers
INCLUDEPATH += $$PWD/../../brick_game
INCLUDEPATH += $$PWD/../../brick_game/snake
INCLUDEPATH += $$PWD/../../brick_game/snake/wrapper
INCLUDEPATH += $$PWD/../../brick_game/tetris

# Link with static libraries built by top-level Makefile
LIBS += -L$$PWD/../.. -lsnake -ltetris
